language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - node_modules

scala:
  - 2.13.2
  - 2.12.11

jdk:
  - oraclejdk8

dist: trusty

before_script:
  - npm install -g kinesalite

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
