language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - node_modules

scala:
  - 2.11.8
  - 2.12.3

jdk:
  - oraclejdk8

before_script:
  - npm install -g kinesalite

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
