language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - node_modules

scala:
  - 2.11.8
  - 2.12.3

jdk:
  - oraclejdk8

before_script:
  - npm install -g kinesalite

script:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then TEST='testOnly * -- -l org.scalatest.tags.Slow'; else TEST="test"; fi
  - sbt ++$TRAVIS_SCALA_VERSION $TEST
